{
  searchAcrossEntities(
    input: {types: [DATASET], query: "*", orFilters: [{and: [{field: "ownershipTypeUrn", values: ["urn:li:ownershipType:__system__data_steward"]}]}], start: 0, count: 10}
  ) {
    start
    count
    total
    searchResults {
      entity {
        urn
        type
        ... on Dataset {
          name
          ownership {
            owners {
              owner {
                ... on CorpUser {
                  urn
                  type
                }
                ... on CorpGroup {
                  urn
                  type
                }
              }
            }
          }
        }
      }
    }
  }
}