query scrollAcrossLineage($input: ScrollAcrossLineageInput!) {
    scrollAcrossLineage(input: $input) {
        nextScrollId
        total
        searchResults {
            degree
            entity {
                urn
                type
            }
        }
    }
}
